name: MVP pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: git checkout
        uses: actions/checkout@v4
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}
      
      - name: ssh into server 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Connect to macOS
        run: |
          scp -o StrictHostKeyChecking=no  ./docker-compose.yml devops@100.80.47.92:./ 
         
          